options:
  old-algorithm: false
  auto-update: true

coal_ore:
  overall_chance: 25
  iron_dust: true
  gold_dust: true
  aluminum_dust: true
  zinc_dust: true
  tin_dust: true
  copper_dust: true
  magnesium_dust: true
  lead_dust: true
  silver_dust: true
iron_ore:
  overall_chance: 25
  iron_dust: true
  gold_dust: true
  aluminum_dust: true
  zinc_dust: true
  tin_dust: true
  copper_dust: true
  magnesium_dust: true
  lead_dust: true
  silver_dust: true
gold_ore:
  overall_chance: 25
  iron_dust: true
  gold_dust: true
  aluminum_dust: true
  zinc_dust: true
  tin_dust: true
  copper_dust: true
  magnesium_dust: true
  lead_dust: true
  silver_dust: true
diamond_ore:
  overall_chance: 25
  iron_dust: true
  gold_dust: true
  aluminum_dust: true
  zinc_dust: true
  tin_dust: true
  copper_dust: true
  magnesium_dust: true
  lead_dust: true
  silver_dust: true
  tiny_uranium: false
emerald_ore:
  overall_chance: 25
  iron_dust: true
  gold_dust: true
  aluminum_dust: true
  zinc_dust: true
  tin_dust: true
  copper_dust: true
  magnesium_dust: true
  lead_dust: true
  silver_dust: true
  tiny_uranium: false