name: SlimefunOres2
author: XWasHere
description: An updated version of the original SlimefunOres
main: org.xwashere.slimefunores.SlimefunOres
version: ${project.version}
api-version: 1.14
## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun